<?php
/**
 * Asset Management with Vite Manifest
 *
 * Handles enqueueing of CSS and JS files generated by Vite.
 * Uses manifest.json for cache busting and version control.
 *
 * @package dbw-base
 * @author  dbw media
 * @link    https://dbw-media.de
 */

if (!defined('ABSPATH')) {
    exit;
}

/**
 * Get Vite Manifest
 *
 * @return array|false Manifest array or false on failure
 */
function dbw_get_vite_manifest() {
    static $manifest = null;

    if ($manifest !== null) {
        return $manifest;
    }

    $manifest_path = DBW_THEME_DIR . '/build/.vite/manifest.json';

    if (!file_exists($manifest_path)) {
        if (defined('WP_DEBUG') && WP_DEBUG) {
            error_log('dbw-base: Vite manifest not found. Run npm run build.');
        }
        $manifest = false;
        return false;
    }

    $manifest_content = file_get_contents($manifest_path);
    $manifest = json_decode($manifest_content, true);

    if (json_last_error() !== JSON_ERROR_NONE) {
        if (defined('WP_DEBUG') && WP_DEBUG) {
            error_log('dbw-base: Invalid JSON in Vite manifest.');
        }
        $manifest = false;
        return false;
    }

    return $manifest;
}

/**
 * Get Asset Path from Manifest
 *
 * @param string $entry Entry name from manifest
 * @param string $type  Type of asset (file, css)
 * @return string|false Asset path or false
 */
function dbw_get_asset_path($entry, $type = 'file') {
    $manifest = dbw_get_vite_manifest();

    if (!$manifest || !isset($manifest[$entry])) {
        return false;
    }

    // For CSS entries, check both 'css' array and 'file' (direct CSS entry)
    if ($type === 'css') {
        if (isset($manifest[$entry]['css'][0])) {
            return $manifest[$entry]['css'][0];
        }
        // If entry itself is a CSS file, use 'file' property
        if (isset($manifest[$entry]['file']) && str_ends_with($manifest[$entry]['file'], '.css')) {
            return $manifest[$entry]['file'];
        }
    }

    if ($type === 'file' && isset($manifest[$entry]['file'])) {
        return $manifest[$entry]['file'];
    }

    return false;
}

/**
 * Enqueue Vite Assets
 */
function dbw_enqueue_vite_assets() {
    $manifest = dbw_get_vite_manifest();

    if (!$manifest) {
        return;
    }

    $css_path = dbw_get_asset_path('src/scss/main.scss', 'css');
    if ($css_path) {
        wp_enqueue_style(
            'dbw-base-styles',
            DBW_THEME_URI . '/build/' . $css_path,
            ['generate-style'],
            null
        );
    }

    $js_path = dbw_get_asset_path('src/js/main.js', 'file');
    if ($js_path) {
        wp_enqueue_script(
            'dbw-base-scripts',
            DBW_THEME_URI . '/build/' . $js_path,
            [],
            null,
            true
        );
    }
}
